[package]
name = "basic_basic_compiler"
version = "0.1.0"
authors = ["Renjith <grenjithr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
